import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

const ACUMEN_QUESTIONS = [
  // EXTERNAL - Understanding Others (1-5)
  {
    questionNumber: 1,
    questionText: 'Cuando conozco a alguien nuevo, evalúo rápidamente sus fortalezas y debilidades.',
    dimension: 'UNDERSTANDING_OTHERS',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 2,
    questionText: 'Puedo percibir las motivaciones y necesidades de las personas incluso cuando no las expresan.',
    dimension: 'UNDERSTANDING_OTHERS',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 3,
    questionText: 'Construyo relaciones de confianza rápidamente con personas de diferentes perfiles.',
    dimension: 'UNDERSTANDING_OTHERS',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 4,
    questionText: 'Detecto señales no verbales y emocionales en las interacciones con otros.',
    dimension: 'UNDERSTANDING_OTHERS',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 5,
    questionText: 'Me resulta fácil anticipar cómo reaccionarán las personas ante diferentes situaciones.',
    dimension: 'UNDERSTANDING_OTHERS',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  
  // EXTERNAL - Practical Thinking (6-10)
  {
    questionNumber: 6,
    questionText: 'Identifico rápidamente las soluciones más prácticas y eficientes para los problemas.',
    dimension: 'PRACTICAL_THINKING',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 7,
    questionText: 'Evalúo las situaciones considerando los recursos disponibles y las limitaciones reales.',
    dimension: 'PRACTICAL_THINKING',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 8,
    questionText: 'Me enfoco en resultados tangibles y medibles cuando trabajo en proyectos.',
    dimension: 'PRACTICAL_THINKING',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 9,
    questionText: 'Distingo claramente entre lo urgente y lo importante en las tareas diarias.',
    dimension: 'PRACTICAL_THINKING',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 10,
    questionText: 'Implemento acciones concretas que generan valor inmediato.',
    dimension: 'PRACTICAL_THINKING',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  
  // EXTERNAL - Systems Judgment (11-15)
  {
    questionNumber: 11,
    questionText: 'Comprendo cómo las diferentes partes de un sistema interactúan entre sí.',
    dimension: 'SYSTEMS_JUDGMENT',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 12,
    questionText: 'Respeto y sigo los procesos y procedimientos establecidos.',
    dimension: 'SYSTEMS_JUDGMENT',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 13,
    questionText: 'Identifico patrones y tendencias en datos y situaciones complejas.',
    dimension: 'SYSTEMS_JUDGMENT',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 14,
    questionText: 'Considero las consecuencias a largo plazo de las decisiones.',
    dimension: 'SYSTEMS_JUDGMENT',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 15,
    questionText: 'Aplico principios y reglas de manera consistente en diferentes situaciones.',
    dimension: 'SYSTEMS_JUDGMENT',
    factor: 'EXTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  
  // INTERNAL - Sense of Self (16-20)
  {
    questionNumber: 16,
    questionText: 'Tengo una comprensión clara de mis fortalezas y debilidades.',
    dimension: 'SENSE_OF_SELF',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 17,
    questionText: 'Me valoro a mí mismo de manera realista, sin sobrestimarme ni subestimarme.',
    dimension: 'SENSE_OF_SELF',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 18,
    questionText: 'Mantengo mi autoestima estable incluso cuando enfrento críticas.',
    dimension: 'SENSE_OF_SELF',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 19,
    questionText: 'Reconozco mis emociones y cómo afectan mi comportamiento.',
    dimension: 'SENSE_OF_SELF',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 20,
    questionText: 'Tengo claridad sobre lo que es verdaderamente importante para mí.',
    dimension: 'SENSE_OF_SELF',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  
  // INTERNAL - Role Awareness (21-25)
  {
    questionNumber: 21,
    questionText: 'Comprendo claramente mis responsabilidades y expectativas en mi rol actual.',
    dimension: 'ROLE_AWARENESS',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 22,
    questionText: 'Ajusto mi comportamiento según el contexto y la situación.',
    dimension: 'ROLE_AWARENESS',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 23,
    questionText: 'Identifico cómo mi trabajo contribuye a los objetivos más amplios de la organización.',
    dimension: 'ROLE_AWARENESS',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 24,
    questionText: 'Equilibro mis necesidades personales con las demandas de mi rol profesional.',
    dimension: 'ROLE_AWARENESS',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 25,
    questionText: 'Me adapto a los cambios en mis roles y responsabilidades.',
    dimension: 'ROLE_AWARENESS',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  
  // INTERNAL - Self Direction (26-30)
  {
    questionNumber: 26,
    questionText: 'Establezco metas claras y planes para alcanzarlas.',
    dimension: 'SELF_DIRECTION',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 27,
    questionText: 'Tomo la iniciativa para mejorar mi desarrollo profesional y personal.',
    dimension: 'SELF_DIRECTION',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 28,
    questionText: 'Mantengo el enfoque en mis objetivos a pesar de las distracciones.',
    dimension: 'SELF_DIRECTION',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 29,
    questionText: 'Gestiono mi tiempo y energía de manera efectiva.',
    dimension: 'SELF_DIRECTION',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 30,
    questionText: 'Me disciplino para hacer lo necesario, incluso cuando no es agradable.',
    dimension: 'SELF_DIRECTION',
    factor: 'INTERNAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
];

export async function POST() {
  try {
    const existingCount = await prisma.acumenQuestion.count();
    
    if (existingCount > 0) {
      return NextResponse.json({
        message: `Ya existen ${existingCount} preguntas Acumen en la base de datos`,
        count: existingCount,
      });
    }
    
    const createdQuestions = await prisma.acumenQuestion.createMany({
      data: ACUMEN_QUESTIONS.map((q) => ({
        ...q,
        dimension: q.dimension as any,
        factor: q.factor as any,
        questionType: 'AGREEMENT' as any,
        isReversed: false,
        weight: 1.0,
        isActive: true,
      })),
    });
    
    return NextResponse.json({
      success: true,
      message: `${createdQuestions.count} preguntas Acumen creadas exitosamente`,
      count: createdQuestions.count,
    });
  } catch (error) {
    console.error('Error seeding Acumen questions:', error);
    return NextResponse.json(
      { error: 'Error al crear las preguntas Acumen' },
      { status: 500 }
    );
  }
}
