// Technical Questions Generator
// Contains base questions for each job category that can be customized

import { JOB_POSITIONS, JobPosition } from './job-positions';

export interface TechnicalQuestionTemplate {
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  category: string;
}

// Get questions for a specific job position
export function getQuestionsForPosition(positionId: string): TechnicalQuestionTemplate[] {
  const position = JOB_POSITIONS.find(p => p.id === positionId);
  if (!position) return getGenericQuestions();
  
  // Check if we have specific questions for this category
  const categoryQuestions = CATEGORY_QUESTIONS[position.category];
  if (categoryQuestions && categoryQuestions.length >= 20) {
    return categoryQuestions.slice(0, 20);
  }
  
  // Fall back to generic business questions
  return getGenericQuestions();
}

// Generic business/professional questions
function getGenericQuestions(): TechnicalQuestionTemplate[] {
  return [
    {
      questionText: '¿Cuál es la mejor práctica para gestionar prioridades en un entorno de trabajo dinámico?',
      optionA: 'Trabajar en todas las tareas simultáneamente',
      optionB: 'Utilizar la matriz de Eisenhower para clasificar tareas por urgencia e importancia',
      optionC: 'Esperar instrucciones del supervisor para cada tarea',
      optionD: 'Completar las tareas en el orden en que llegan',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Gestión del Tiempo',
    },
    {
      questionText: '¿Qué elemento es fundamental para una comunicación efectiva en equipos?',
      optionA: 'Usar solo comunicación escrita para evitar malentendidos',
      optionB: 'Escucha activa y retroalimentación constructiva',
      optionC: 'Limitar las reuniones al mínimo posible',
      optionD: 'Comunicar solo cuando sea absolutamente necesario',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Comunicación',
    },
    {
      questionText: '¿Cuál es el primer paso recomendado ante un conflicto laboral?',
      optionA: 'Escalar inmediatamente al supervisor',
      optionB: 'Ignorar el conflicto hasta que se resuelva solo',
      optionC: 'Identificar las causas raíz y buscar un diálogo constructivo',
      optionD: 'Documentar todo para protegerse',
      correctAnswer: 'C',
      difficulty: 'MEDIUM',
      category: 'Resolución de Conflictos',
    },
    {
      questionText: '¿Qué característica define a un líder transformacional?',
      optionA: 'Enfoque exclusivo en resultados financieros',
      optionB: 'Inspirar y motivar al equipo hacia una visión compartida',
      optionC: 'Control estricto de todas las actividades del equipo',
      optionD: 'Delegar todas las decisiones al equipo',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Liderazgo',
    },
    {
      questionText: '¿Qué metodología se utiliza para mejora continua de procesos?',
      optionA: 'FIFO (First In, First Out)',
      optionB: 'PDCA (Plan-Do-Check-Act)',
      optionC: 'LIFO (Last In, First Out)',
      optionD: 'ABC Analysis',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Mejora de Procesos',
    },
    {
      questionText: '¿Cuál es el objetivo principal del trabajo en equipo?',
      optionA: 'Distribuir la carga de trabajo equitativamente',
      optionB: 'Lograr resultados superiores mediante la colaboración y sinergia',
      optionC: 'Reducir la responsabilidad individual',
      optionD: 'Socializar con los compañeros',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Trabajo en Equipo',
    },
    {
      questionText: '¿Qué es la inteligencia emocional en el contexto laboral?',
      optionA: 'Coeficiente intelectual alto',
      optionB: 'Capacidad de reconocer y gestionar las emociones propias y ajenas',
      optionC: 'Habilidad para memorizar información',
      optionD: 'Conocimiento técnico especializado',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Habilidades Blandas',
    },
    {
      questionText: '¿Cuál es la mejor estrategia para adaptarse al cambio organizacional?',
      optionA: 'Resistirse hasta que se demuestre su beneficio',
      optionB: 'Mantener una actitud flexible y buscar oportunidades de aprendizaje',
      optionC: 'Esperar a que otros se adapten primero',
      optionD: 'Ignorar los cambios y continuar como antes',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Adaptabilidad',
    },
    {
      questionText: '¿Qué elemento es clave para la toma de decisiones efectiva?',
      optionA: 'Decidir rápidamente sin análisis',
      optionB: 'Recopilar información relevante y evaluar alternativas',
      optionC: 'Seguir siempre la intuición',
      optionD: 'Delegar todas las decisiones',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Toma de Decisiones',
    },
    {
      questionText: '¿Qué representa el principio de Pareto (80/20)?',
      optionA: 'El 80% del trabajo debe hacerse en el 20% del tiempo',
      optionB: 'El 80% de los resultados provienen del 20% de los esfuerzos',
      optionC: 'El 80% de los empleados hacen el 20% del trabajo',
      optionD: 'El 80% del presupuesto va a salarios',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Productividad',
    },
    {
      questionText: '¿Qué es el pensamiento crítico?',
      optionA: 'Criticar el trabajo de los demás',
      optionB: 'Analizar información objetivamente para formar juicios fundamentados',
      optionC: 'Aceptar información sin cuestionarla',
      optionD: 'Pensar de forma negativa',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Pensamiento Analítico',
    },
    {
      questionText: '¿Cuál es el propósito principal de establecer metas SMART?',
      optionA: 'Parecer más inteligente',
      optionB: 'Crear objetivos específicos, medibles, alcanzables, relevantes y con tiempo definido',
      optionC: 'Establecer metas ambiguas para mayor flexibilidad',
      optionD: 'Reducir la presión del trabajo',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Planificación',
    },
    {
      questionText: '¿Qué implica la ética profesional?',
      optionA: 'Seguir reglas solo cuando hay supervisión',
      optionB: 'Actuar con integridad, honestidad y responsabilidad en el trabajo',
      optionC: 'Hacer lo mínimo necesario',
      optionD: 'Priorizar siempre los intereses personales',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Ética Profesional',
    },
    {
      questionText: '¿Qué es la gestión del conocimiento en una organización?',
      optionA: 'Mantener información confidencial',
      optionB: 'Capturar, organizar y compartir el conocimiento para mejorar el rendimiento',
      optionC: 'Memorizar todos los procedimientos',
      optionD: 'Limitar el acceso a la información',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Gestión del Conocimiento',
    },
    {
      questionText: '¿Cuál es una característica del pensamiento innovador?',
      optionA: 'Seguir siempre los métodos establecidos',
      optionB: 'Buscar nuevas soluciones y cuestionar el status quo',
      optionC: 'Evitar el riesgo a toda costa',
      optionD: 'Copiar lo que hacen los competidores',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Innovación',
    },
    {
      questionText: '¿Qué significa ser proactivo en el trabajo?',
      optionA: 'Esperar instrucciones antes de actuar',
      optionB: 'Anticipar necesidades y tomar iniciativa antes de que se solicite',
      optionC: 'Reaccionar solo ante problemas urgentes',
      optionD: 'Hacer solo lo que está en la descripción del puesto',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Iniciativa',
    },
    {
      questionText: '¿Qué es el feedback constructivo?',
      optionA: 'Crítica negativa para señalar errores',
      optionB: 'Retroalimentación específica y orientada a la mejora',
      optionC: 'Elogios generales sin detalles',
      optionD: 'Comentarios sobre la personalidad',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Comunicación',
    },
    {
      questionText: '¿Cuál es el beneficio principal de la delegación efectiva?',
      optionA: 'Reducir la responsabilidad personal',
      optionB: 'Desarrollar las capacidades del equipo y optimizar recursos',
      optionC: 'Tener menos trabajo que hacer',
      optionD: 'Demostrar autoridad',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Liderazgo',
    },
    {
      questionText: '¿Qué es la resiliencia en el contexto profesional?',
      optionA: 'Rigidez ante los cambios',
      optionB: 'Capacidad de recuperarse y adaptarse ante adversidades',
      optionC: 'Evitar situaciones difíciles',
      optionD: 'Ignorar los problemas',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Resiliencia',
    },
    {
      questionText: '¿Qué elemento es esencial para la gestión de proyectos exitosa?',
      optionA: 'Trabajar sin un plan definido',
      optionB: 'Planificación, seguimiento y comunicación continua',
      optionC: 'Evitar documentar los avances',
      optionD: 'Trabajar de forma aislada',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Gestión de Proyectos',
    },
  ];
}

// Questions by job category
const CATEGORY_QUESTIONS: Partial<Record<string, TechnicalQuestionTemplate[]>> = {
  TECNOLOGIA_IT: [
    // Programming & Software Development
    {
      questionText: '¿Qué principio de programación establece que cada módulo debe tener una única responsabilidad?',
      optionA: 'DRY (Don\'t Repeat Yourself)',
      optionB: 'KISS (Keep It Simple, Stupid)',
      optionC: 'SRP (Single Responsibility Principle)',
      optionD: 'YAGNI (You Aren\'t Gonna Need It)',
      correctAnswer: 'C',
      difficulty: 'MEDIUM',
      category: 'Principios de Programación',
    },
    {
      questionText: '¿Cuál es la complejidad temporal de buscar un elemento en un HashMap?',
      optionA: 'O(n)',
      optionB: 'O(log n)',
      optionC: 'O(n²)',
      optionD: 'O(1) en promedio',
      correctAnswer: 'D',
      difficulty: 'HARD',
      category: 'Estructuras de Datos',
    },
    {
      questionText: '¿Qué patrón de diseño se utiliza para garantizar una única instancia de una clase?',
      optionA: 'Factory',
      optionB: 'Singleton',
      optionC: 'Observer',
      optionD: 'Strategy',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Patrones de Diseño',
    },
    {
      questionText: '¿Qué es una API RESTful?',
      optionA: 'Una base de datos relacional',
      optionB: 'Un estilo arquitectónico para servicios web usando métodos HTTP estándar',
      optionC: 'Un lenguaje de programación',
      optionD: 'Un protocolo de seguridad',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Desarrollo Web',
    },
    {
      questionText: '¿Cuál es la diferencia principal entre Git merge y Git rebase?',
      optionA: 'No hay diferencia',
      optionB: 'Merge crea un commit de fusión, rebase reescribe el historial',
      optionC: 'Rebase es más rápido',
      optionD: 'Merge solo funciona localmente',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Control de Versiones',
    },
    {
      questionText: '¿Qué es CI/CD en el contexto de desarrollo de software?',
      optionA: 'Código Interno / Código Distribuido',
      optionB: 'Integración Continua / Despliegue Continuo',
      optionC: 'Configuración Inicial / Configuración Diferida',
      optionD: 'Control de Incidencias / Control de Defectos',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'DevOps',
    },
    {
      questionText: '¿Qué tipo de base de datos es MongoDB?',
      optionA: 'Relacional',
      optionB: 'Documental (NoSQL)',
      optionC: 'Grafo',
      optionD: 'Clave-Valor',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Bases de Datos',
    },
    {
      questionText: '¿Qué es un microservicio?',
      optionA: 'Un servicio muy pequeño que no hace mucho',
      optionB: 'Una arquitectura donde las aplicaciones se dividen en servicios independientes',
      optionC: 'Un tipo de servidor web',
      optionD: 'Una biblioteca de JavaScript',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Arquitectura',
    },
    {
      questionText: '¿Cuál es el propósito principal de Docker?',
      optionA: 'Programar en Python',
      optionB: 'Containerizar aplicaciones para portabilidad y consistencia',
      optionC: 'Crear interfaces gráficas',
      optionD: 'Gestionar bases de datos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'DevOps',
    },
    {
      questionText: '¿Qué es una inyección SQL?',
      optionA: 'Una forma de optimizar consultas',
      optionB: 'Un ataque donde se insertan comandos SQL maliciosos',
      optionC: 'Un método de backup',
      optionD: 'Un tipo de índice de base de datos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Seguridad',
    },
    {
      questionText: '¿Qué significa SOLID en programación orientada a objetos?',
      optionA: 'Un tipo de base de datos',
      optionB: 'Cinco principios de diseño de software',
      optionC: 'Un framework de JavaScript',
      optionD: 'Un método de testing',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Principios de Programación',
    },
    {
      questionText: '¿Cuál es la diferencia entre == y === en JavaScript?',
      optionA: 'No hay diferencia',
      optionB: '== compara valor, === compara valor y tipo',
      optionC: '=== es más lento',
      optionD: '== solo funciona con números',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'JavaScript',
    },
    {
      questionText: '¿Qué es un webhook?',
      optionA: 'Una herramienta de debugging',
      optionB: 'Una llamada HTTP automática cuando ocurre un evento',
      optionC: 'Un tipo de base de datos',
      optionD: 'Un framework de testing',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Integración',
    },
    {
      questionText: '¿Qué es TDD (Test-Driven Development)?',
      optionA: 'Testear después de terminar el código',
      optionB: 'Escribir tests antes del código de producción',
      optionC: 'No escribir tests',
      optionD: 'Testear solo en producción',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Testing',
    },
    {
      questionText: '¿Cuál es el propósito de un load balancer?',
      optionA: 'Aumentar el tamaño de los servidores',
      optionB: 'Distribuir tráfico entre múltiples servidores',
      optionC: 'Comprimir datos',
      optionD: 'Encriptar comunicaciones',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Infraestructura',
    },
    {
      questionText: '¿Qué es GraphQL?',
      optionA: 'Una base de datos de grafos',
      optionB: 'Un lenguaje de consulta para APIs',
      optionC: 'Un framework de frontend',
      optionD: 'Un servicio de hosting',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'APIs',
    },
    {
      questionText: '¿Qué protocolo se usa comúnmente para comunicación en tiempo real en web?',
      optionA: 'FTP',
      optionB: 'WebSocket',
      optionC: 'SMTP',
      optionD: 'POP3',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Protocolos',
    },
    {
      questionText: '¿Qué es el principio DRY?',
      optionA: 'Documentar todo el código',
      optionB: 'No repetir código, reutilizar funcionalidad',
      optionC: 'Escribir código rápidamente',
      optionD: 'Usar solo funciones asíncronas',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Principios de Programación',
    },
    {
      questionText: '¿Cuál es la función de un CDN (Content Delivery Network)?',
      optionA: 'Crear contenido dinámico',
      optionB: 'Distribuir contenido geográficamente para reducir latencia',
      optionC: 'Compilar código',
      optionD: 'Gestionar bases de datos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Infraestructura',
    },
    {
      questionText: '¿Qué es Agile/Scrum?',
      optionA: 'Un lenguaje de programación',
      optionB: 'Una metodología iterativa de desarrollo de software',
      optionC: 'Un tipo de base de datos',
      optionD: 'Una herramienta de deployment',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Metodologías',
    },
  ],
  
  ADMINISTRACION_FINANZAS: [
    {
      questionText: '¿Qué representa el activo en un balance general?',
      optionA: 'Las deudas de la empresa',
      optionB: 'Los recursos y bienes que posee la empresa',
      optionC: 'Los gastos del período',
      optionD: 'Los ingresos del período',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Contabilidad',
    },
    {
      questionText: '¿Cuál es la fórmula del ROI (Return on Investment)?',
      optionA: 'Ingresos / Gastos',
      optionB: '(Ganancia - Inversión) / Inversión × 100',
      optionC: 'Activos / Pasivos',
      optionD: 'Ventas - Costos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Análisis Financiero',
    },
    {
      questionText: '¿Qué es el flujo de caja?',
      optionA: 'Las ventas totales de un período',
      optionB: 'El movimiento de dinero que entra y sale de la empresa',
      optionC: 'Los activos fijos de la empresa',
      optionD: 'El patrimonio neto',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Finanzas',
    },
    {
      questionText: '¿Qué indica un ratio de liquidez corriente mayor a 1?',
      optionA: 'La empresa tiene problemas de liquidez',
      optionB: 'La empresa puede cubrir sus obligaciones a corto plazo',
      optionC: 'La empresa tiene demasiadas deudas',
      optionD: 'La empresa está en bancarrota',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Análisis Financiero',
    },
    {
      questionText: '¿Qué es la depreciación?',
      optionA: 'El aumento del valor de los activos',
      optionB: 'La distribución del costo de un activo durante su vida útil',
      optionC: 'El pago de intereses',
      optionD: 'La venta de activos',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Contabilidad',
    },
    {
      questionText: '¿Cuál es la diferencia entre costo fijo y costo variable?',
      optionA: 'No hay diferencia',
      optionB: 'Los costos fijos no cambian con el volumen de producción, los variables sí',
      optionC: 'Los costos fijos son más altos',
      optionD: 'Los costos variables son siempre negativos',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Costos',
    },
    {
      questionText: '¿Qué es el punto de equilibrio?',
      optionA: 'El máximo de ganancias posible',
      optionB: 'El nivel de ventas donde los ingresos igualan los costos totales',
      optionC: 'El mínimo de producción',
      optionD: 'El momento de cerrar el negocio',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Análisis de Costos',
    },
    {
      questionText: '¿Qué representa el EBITDA?',
      optionA: 'El efectivo disponible',
      optionB: 'Ganancias antes de intereses, impuestos, depreciación y amortización',
      optionC: 'El total de activos',
      optionD: 'Las deudas a largo plazo',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Análisis Financiero',
    },
    {
      questionText: '¿Qué es una auditoría interna?',
      optionA: 'Revisión realizada por el gobierno',
      optionB: 'Evaluación independiente de los procesos y controles de la organización',
      optionC: 'Contratación de personal',
      optionD: 'Venta de activos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Auditoría',
    },
    {
      questionText: '¿Qué principio contable establece que los gastos deben reconocerse en el período en que se incurren?',
      optionA: 'Principio de conservadurismo',
      optionB: 'Principio de devengo',
      optionC: 'Principio de materialidad',
      optionD: 'Principio de entidad',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Principios Contables',
    },
    {
      questionText: '¿Qué es el capital de trabajo?',
      optionA: 'El dinero para comprar equipos',
      optionB: 'Activo corriente menos pasivo corriente',
      optionC: 'El patrimonio total',
      optionD: 'Los préstamos bancarios',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Finanzas',
    },
    {
      questionText: '¿Qué es la conciliación bancaria?',
      optionA: 'Abrir una cuenta bancaria',
      optionB: 'Comparar registros contables con los estados de cuenta bancarios',
      optionC: 'Transferir dinero entre cuentas',
      optionD: 'Solicitar un préstamo',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Tesorería',
    },
    {
      questionText: '¿Qué es el apalancamiento financiero?',
      optionA: 'Tener mucho efectivo',
      optionB: 'Usar deuda para financiar activos y aumentar el retorno potencial',
      optionC: 'Reducir los gastos',
      optionD: 'Aumentar los precios',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Finanzas',
    },
    {
      questionText: '¿Qué es el presupuesto base cero?',
      optionA: 'Un presupuesto sin límites',
      optionB: 'Justificar cada gasto desde cero sin basarse en períodos anteriores',
      optionC: 'Un presupuesto que no incluye gastos',
      optionD: 'El presupuesto del primer año',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Presupuestos',
    },
    {
      questionText: '¿Qué documento registra las transacciones diarias de una empresa?',
      optionA: 'Balance General',
      optionB: 'Libro Diario',
      optionC: 'Estado de Resultados',
      optionD: 'Presupuesto',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Contabilidad',
    },
    {
      questionText: '¿Qué indica el ratio Deuda/Patrimonio?',
      optionA: 'La rentabilidad de la empresa',
      optionB: 'El nivel de endeudamiento respecto al capital propio',
      optionC: 'La liquidez de la empresa',
      optionD: 'Las ventas totales',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Análisis Financiero',
    },
    {
      questionText: '¿Qué es el VAN (Valor Actual Neto)?',
      optionA: 'El valor total de los activos',
      optionB: 'El valor presente de los flujos de caja futuros menos la inversión inicial',
      optionC: 'Las ventas netas',
      optionD: 'El margen de ganancia',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Evaluación de Proyectos',
    },
    {
      questionText: '¿Qué son los gastos operativos?',
      optionA: 'Gastos relacionados con la operación diaria del negocio',
      optionB: 'Gastos de capital',
      optionC: 'Impuestos',
      optionD: 'Intereses de préstamos',
      correctAnswer: 'A',
      difficulty: 'EASY',
      category: 'Costos',
    },
    {
      questionText: '¿Qué es la TIR (Tasa Interna de Retorno)?',
      optionA: 'La tasa de impuestos',
      optionB: 'La tasa de descuento que hace el VAN igual a cero',
      optionC: 'La tasa de inflación',
      optionD: 'La tasa de interés bancaria',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Evaluación de Proyectos',
    },
    {
      questionText: '¿Cuál es el objetivo principal del control interno?',
      optionA: 'Aumentar las ventas',
      optionB: 'Proteger los activos y asegurar la confiabilidad de la información financiera',
      optionC: 'Reducir el personal',
      optionD: 'Eliminar todos los riesgos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Control Interno',
    },
  ],
  
  VENTAS_COMERCIAL: [
    {
      questionText: '¿Cuál es el primer paso en el proceso de ventas?',
      optionA: 'Cerrar la venta',
      optionB: 'Prospección e identificación de clientes potenciales',
      optionC: 'Negociar el precio',
      optionD: 'Entregar el producto',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Proceso de Ventas',
    },
    {
      questionText: '¿Qué técnica de ventas implica identificar las necesidades del cliente antes de presentar soluciones?',
      optionA: 'Venta a presión',
      optionB: 'Venta consultiva',
      optionC: 'Venta por catálogo',
      optionD: 'Venta por impulso',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Técnicas de Venta',
    },
    {
      questionText: '¿Qué es el SPIN Selling?',
      optionA: 'Una técnica de venta rápida',
      optionB: 'Una metodología basada en preguntas de Situación, Problema, Implicación y Necesidad',
      optionC: 'Un software de ventas',
      optionD: 'Un tipo de descuento',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Metodologías de Venta',
    },
    {
      questionText: '¿Qué significa CRM?',
      optionA: 'Control de Recursos de Marketing',
      optionB: 'Customer Relationship Management',
      optionC: 'Centro de Reclamos Masivos',
      optionD: 'Costos de Retención de Mercado',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Herramientas',
    },
    {
      questionText: '¿Cuál es una objeción de venta común y cómo se maneja mejor?',
      optionA: 'Ignorar la objeción',
      optionB: 'Escuchar, entender y responder con beneficios relevantes',
      optionC: 'Ofrecer inmediatamente un descuento',
      optionD: 'Pasar a otro cliente',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Manejo de Objeciones',
    },
    {
      questionText: '¿Qué es el funnel o embudo de ventas?',
      optionA: 'Un tipo de descuento',
      optionB: 'El proceso por el cual los prospectos se convierten en clientes',
      optionC: 'Una estrategia de precios',
      optionD: 'Un formulario de pedido',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Proceso de Ventas',
    },
    {
      questionText: '¿Qué es cross-selling?',
      optionA: 'Vender a competidores',
      optionB: 'Ofrecer productos complementarios al cliente',
      optionC: 'Reducir precios',
      optionD: 'Vender en diferentes países',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Estrategias de Venta',
    },
    {
      questionText: '¿Cuál es la diferencia entre características y beneficios de un producto?',
      optionA: 'Son lo mismo',
      optionB: 'Las características describen el producto, los beneficios explican cómo ayuda al cliente',
      optionC: 'Los beneficios son más técnicos',
      optionD: 'Las características son subjetivas',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Presentación',
    },
    {
      questionText: '¿Qué es up-selling?',
      optionA: 'Vender productos de menor calidad',
      optionB: 'Ofrecer una versión superior o premium del producto',
      optionC: 'Reducir el precio de venta',
      optionD: 'Vender en grandes cantidades',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Estrategias de Venta',
    },
    {
      questionText: '¿Qué indica el KPI "tasa de conversión"?',
      optionA: 'El número total de ventas',
      optionB: 'El porcentaje de prospectos que se convierten en clientes',
      optionC: 'El tiempo promedio de venta',
      optionD: 'El margen de ganancia',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Métricas',
    },
    {
      questionText: '¿Qué es el "elevator pitch"?',
      optionA: 'Una presentación en un ascensor',
      optionB: 'Una presentación breve y convincente de tu propuesta de valor',
      optionC: 'Una técnica de cierre',
      optionD: 'Un tipo de descuento',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Presentación',
    },
    {
      questionText: '¿Qué técnica de cierre implica asumir que el cliente ya decidió comprar?',
      optionA: 'Cierre por urgencia',
      optionB: 'Cierre presuntivo o asuntivo',
      optionC: 'Cierre por descuento',
      optionD: 'Cierre por características',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Técnicas de Cierre',
    },
    {
      questionText: '¿Qué significa CAC en ventas?',
      optionA: 'Control de Actividades Comerciales',
      optionB: 'Costo de Adquisición de Cliente',
      optionC: 'Ciclo de Actividad Comercial',
      optionD: 'Centro de Atención al Cliente',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Métricas',
    },
    {
      questionText: '¿Cuál es la importancia del seguimiento post-venta?',
      optionA: 'No es importante',
      optionB: 'Aumenta la satisfacción, fidelización y oportunidades de nuevas ventas',
      optionC: 'Solo es necesario si hay problemas',
      optionD: 'Es responsabilidad de otro departamento',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Servicio Post-Venta',
    },
    {
      questionText: '¿Qué es el "buyer persona"?',
      optionA: 'El comprador real',
      optionB: 'Una representación semi-ficticia del cliente ideal',
      optionC: 'El jefe de compras',
      optionD: 'Un tipo de vendedor',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Estrategia',
    },
    {
      questionText: '¿Qué representa el "lifetime value" (LTV) de un cliente?',
      optionA: 'El valor de la primera compra',
      optionB: 'El valor total que un cliente genera durante toda su relación con la empresa',
      optionC: 'El tiempo que tarda en comprar',
      optionD: 'El número de productos que compra',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Métricas',
    },
    {
      questionText: '¿Cuál es una señal de compra del cliente?',
      optionA: 'El cliente se va sin decir nada',
      optionB: 'El cliente pregunta sobre disponibilidad, garantía o formas de pago',
      optionC: 'El cliente dice que no tiene tiempo',
      optionD: 'El cliente menciona a la competencia',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Señales de Compra',
    },
    {
      questionText: '¿Qué es la "propuesta de valor"?',
      optionA: 'El precio del producto',
      optionB: 'Lo que diferencia tu producto y por qué el cliente debe elegirte',
      optionC: 'Un tipo de descuento',
      optionD: 'El catálogo de productos',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Estrategia',
    },
    {
      questionText: '¿Qué es un "lead calificado"?',
      optionA: 'Cualquier contacto',
      optionB: 'Un prospecto que ha mostrado interés y cumple criterios para ser cliente',
      optionC: 'Un cliente existente',
      optionD: 'Un empleado de ventas',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Prospección',
    },
    {
      questionText: '¿Qué es el "social selling"?',
      optionA: 'Vender productos sociales',
      optionB: 'Usar redes sociales para identificar, conectar y cultivar relaciones con prospectos',
      optionC: 'Vender en eventos sociales',
      optionD: 'Vender productos a ONGs',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Estrategias Digitales',
    },
  ],
  
  RECURSOS_HUMANOS: [
    {
      questionText: '¿Cuál es el primer paso en un proceso de selección efectivo?',
      optionA: 'Realizar entrevistas',
      optionB: 'Definir el perfil del puesto y las competencias requeridas',
      optionC: 'Publicar la vacante',
      optionD: 'Revisar CVs',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Selección',
    },
    {
      questionText: '¿Qué es la evaluación por competencias?',
      optionA: 'Evaluar solo conocimientos técnicos',
      optionB: 'Evaluar conocimientos, habilidades y comportamientos relacionados con el desempeño',
      optionC: 'Evaluar la antigüedad',
      optionD: 'Evaluar solo la formación académica',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Evaluación',
    },
    {
      questionText: '¿Qué es el onboarding?',
      optionA: 'El proceso de despido',
      optionB: 'El proceso de integración de nuevos empleados a la organización',
      optionC: 'Una promoción laboral',
      optionD: 'Un tipo de capacitación técnica',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Integración',
    },
    {
      questionText: '¿Cuál es el objetivo principal de una entrevista por competencias?',
      optionA: 'Verificar referencias',
      optionB: 'Obtener ejemplos concretos de comportamientos pasados que predigan desempeño futuro',
      optionC: 'Negociar salario',
      optionD: 'Conocer la personalidad del candidato',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Selección',
    },
    {
      questionText: '¿Qué es el clima organizacional?',
      optionA: 'La temperatura de la oficina',
      optionB: 'La percepción que tienen los empleados sobre su ambiente de trabajo',
      optionC: 'El horario de trabajo',
      optionD: 'Las políticas de la empresa',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Cultura Organizacional',
    },
    {
      questionText: '¿Qué significa KPI en el contexto de RRHH?',
      optionA: 'Knowledge Progress Indicator',
      optionB: 'Key Performance Indicator',
      optionC: 'Key Personnel Index',
      optionD: 'Knowledge People Integration',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Métricas',
    },
    {
      questionText: '¿Qué es la rotación de personal?',
      optionA: 'Cambio de departamento',
      optionB: 'El porcentaje de empleados que dejan la organización en un período',
      optionC: 'Rotación de turnos',
      optionD: 'Promociones internas',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Métricas',
    },
    {
      questionText: '¿Cuál es la diferencia entre capacitación y desarrollo?',
      optionA: 'Son lo mismo',
      optionB: 'Capacitación es para el puesto actual, desarrollo es para crecimiento futuro',
      optionC: 'Desarrollo es más corto',
      optionD: 'Capacitación es solo para gerentes',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Desarrollo',
    },
    {
      questionText: '¿Qué es la evaluación 360 grados?',
      optionA: 'Una evaluación del jefe directo',
      optionB: 'Retroalimentación de múltiples fuentes: jefe, pares, subordinados y clientes',
      optionC: 'Una evaluación anual',
      optionD: 'Una autoevaluación',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Evaluación',
    },
    {
      questionText: '¿Qué es el employer branding?',
      optionA: 'La marca de productos de la empresa',
      optionB: 'La imagen de la empresa como empleador para atraer talento',
      optionC: 'El logo de la empresa',
      optionD: 'El nombre comercial',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Atracción de Talento',
    },
    {
      questionText: '¿Qué es un plan de sucesión?',
      optionA: 'Un plan de despidos',
      optionB: 'Identificar y desarrollar talento interno para posiciones clave futuras',
      optionC: 'Un plan de vacaciones',
      optionD: 'Un tipo de compensación',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Planificación',
    },
    {
      questionText: '¿Cuál es el objetivo del análisis de puesto?',
      optionA: 'Eliminar puestos innecesarios',
      optionB: 'Documentar responsabilidades, requisitos y condiciones de cada posición',
      optionC: 'Reducir salarios',
      optionD: 'Promover empleados',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Estructura Organizacional',
    },
    {
      questionText: '¿Qué es el engagement laboral?',
      optionA: 'Un contrato de trabajo',
      optionB: 'El nivel de compromiso emocional e intelectual del empleado con la organización',
      optionC: 'La puntualidad del empleado',
      optionD: 'Las horas extra trabajadas',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Cultura Organizacional',
    },
    {
      questionText: '¿Qué indica el índice de ausentismo?',
      optionA: 'El número de vacaciones',
      optionB: 'La proporción de tiempo laboral perdido por ausencias',
      optionC: 'El número de empleados',
      optionD: 'Los días festivos',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Métricas',
    },
    {
      questionText: '¿Qué es la compensación variable?',
      optionA: 'El salario base',
      optionB: 'Pagos adicionales basados en el desempeño o resultados',
      optionC: 'Los beneficios de ley',
      optionD: 'Las deducciones de nómina',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Compensaciones',
    },
    {
      questionText: '¿Qué es el assessment center?',
      optionA: 'Un centro de trabajo',
      optionB: 'Una metodología de evaluación con múltiples técnicas y evaluadores',
      optionC: 'Un software de RRHH',
      optionD: 'Un departamento de la empresa',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Selección',
    },
    {
      questionText: '¿Cuál es el propósito de las entrevistas de salida?',
      optionA: 'Convencer al empleado de quedarse',
      optionB: 'Obtener retroalimentación sobre la experiencia y razones de salida',
      optionC: 'Calcular la liquidación',
      optionD: 'Entregar documentos',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Retención',
    },
    {
      questionText: '¿Qué es el DNC (Diagnóstico de Necesidades de Capacitación)?',
      optionA: 'Un título profesional',
      optionB: 'Proceso para identificar brechas entre competencias actuales y requeridas',
      optionC: 'Un tipo de evaluación de desempeño',
      optionD: 'Un documento legal',
      correctAnswer: 'B',
      difficulty: 'MEDIUM',
      category: 'Capacitación',
    },
    {
      questionText: '¿Qué es el headhunting?',
      optionA: 'Despedir empleados',
      optionB: 'Búsqueda activa de talento específico, generalmente ejecutivos o especialistas',
      optionC: 'Publicar vacantes en línea',
      optionD: 'Contratar practicantes',
      correctAnswer: 'B',
      difficulty: 'EASY',
      category: 'Reclutamiento',
    },
    {
      questionText: '¿Qué aspectos considera la equidad interna en compensaciones?',
      optionA: 'Solo el salario de mercado',
      optionB: 'Que puestos de igual valor dentro de la organización tengan compensación similar',
      optionC: 'Solo la antigüedad',
      optionD: 'Solo el título del puesto',
      correctAnswer: 'B',
      difficulty: 'HARD',
      category: 'Compensaciones',
    },
  ],
};

// Export for use in seeding
export { CATEGORY_QUESTIONS };
