import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

// Values questions based on Spranger/Allport model
const QUESTIONS = [
  // TEORICO - Knowledge seeking (5 questions)
  {
    questionNumber: 1,
    questionText: 'Busco constantemente aprender cosas nuevas y expandir mi conocimiento.',
    dimension: 'TEORICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 2,
    questionText: 'Prefiero tomar decisiones basadas en datos y evidencia.',
    dimension: 'TEORICO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 3,
    questionText: 'Me siento satisfecho cuando resuelvo problemas complejos.',
    dimension: 'TEORICO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 4,
    questionText: 'Disfruto investigar y profundizar en temas de mi interés.',
    dimension: 'TEORICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 5,
    questionText: 'Valoro las discusiones intelectuales y el intercambio de ideas.',
    dimension: 'TEORICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  // UTILITARIO - ROI focused (5 questions)
  {
    questionNumber: 6,
    questionText: 'Evalúo las oportunidades principalmente por su potencial de retorno económico.',
    dimension: 'UTILITARIO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 7,
    questionText: 'El éxito financiero es una medida importante de mis logros.',
    dimension: 'UTILITARIO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 8,
    questionText: 'Busco optimizar recursos y maximizar la eficiencia en mi trabajo.',
    dimension: 'UTILITARIO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 9,
    questionText: 'Considero importante acumular recursos y seguridad financiera.',
    dimension: 'UTILITARIO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 10,
    questionText: 'Mido el valor de mis actividades por sus resultados tangibles.',
    dimension: 'UTILITARIO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  // ESTETICO - Harmony and beauty (5 questions)
  {
    questionNumber: 11,
    questionText: 'Aprecio la belleza y armonía en mi entorno.',
    dimension: 'ESTETICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 12,
    questionText: 'Las experiencias creativas y artísticas enriquecen mi vida.',
    dimension: 'ESTETICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 13,
    questionText: 'Valoro el diseño y la presentación en los proyectos que desarrollo.',
    dimension: 'ESTETICO',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 14,
    questionText: 'Busco equilibrio y armonía en mis relaciones y actividades.',
    dimension: 'ESTETICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 15,
    questionText: 'Me inspiran las expresiones artísticas y la creatividad.',
    dimension: 'ESTETICO',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  // SOCIAL - Helping others (5 questions)
  {
    questionNumber: 16,
    questionText: 'Me siento motivado a ayudar a otros a alcanzar sus metas.',
    dimension: 'SOCIAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 17,
    questionText: 'Contribuir al bienestar de mi comunidad es importante para mí.',
    dimension: 'SOCIAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 18,
    questionText: 'Priorizo el impacto social de mis decisiones profesionales.',
    dimension: 'SOCIAL',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 19,
    questionText: 'Dedico tiempo a actividades de voluntariado o apoyo a otros.',
    dimension: 'SOCIAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 20,
    questionText: 'El trabajo en equipo y la colaboración son fundamentales para mí.',
    dimension: 'SOCIAL',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  // INDIVIDUALISTA - Power and influence (5 questions)
  {
    questionNumber: 21,
    questionText: 'Busco posiciones de liderazgo e influencia.',
    dimension: 'INDIVIDUALISTA',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 22,
    questionText: 'El reconocimiento por mis logros es importante para mí.',
    dimension: 'INDIVIDUALISTA',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 23,
    questionText: 'Disfruto dirigir proyectos y tomar decisiones importantes.',
    dimension: 'INDIVIDUALISTA',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 24,
    questionText: 'Aspiro a destacar y ser reconocido en mi campo.',
    dimension: 'INDIVIDUALISTA',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 25,
    questionText: 'Valoro la autonomía y la independencia en mi trabajo.',
    dimension: 'INDIVIDUALISTA',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  // TRADICIONAL - Order and system (5 questions)
  {
    questionNumber: 26,
    questionText: 'Valoro las tradiciones y estructuras establecidas.',
    dimension: 'TRADICIONAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 27,
    questionText: 'El orden y la organización son fundamentales en mi vida.',
    dimension: 'TRADICIONAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 28,
    questionText: 'Respeto y sigo los procesos y políticas establecidas.',
    dimension: 'TRADICIONAL',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 29,
    questionText: 'Creo que las reglas y sistemas existen por buenas razones.',
    dimension: 'TRADICIONAL',
    category: 'PROFESSIONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
  {
    questionNumber: 30,
    questionText: 'Prefiero la estabilidad y la consistencia sobre el cambio constante.',
    dimension: 'TRADICIONAL',
    category: 'PERSONAL',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
  },
];

export async function POST() {
  try {
    // Check if questions already exist
    const existingCount = await prisma.valuesQuestion.count();
    if (existingCount > 0) {
      return NextResponse.json({
        success: true,
        message: 'Las preguntas de Valores ya existen',
        count: existingCount,
      });
    }

    // Create all questions
    for (const q of QUESTIONS) {
      await prisma.valuesQuestion.create({
        data: {
          questionNumber: q.questionNumber,
          questionText: q.questionText,
          dimension: q.dimension as any,
          category: q.category as any,
          optionA: q.optionA,
          optionB: q.optionB,
          optionC: q.optionC,
          optionD: q.optionD,
          optionE: q.optionE,
        },
      });
    }

    return NextResponse.json({
      success: true,
      message: `${QUESTIONS.length} preguntas de Valores creadas exitosamente`,
      count: QUESTIONS.length,
    });
  } catch (error) {
    console.error('Error seeding values questions:', error);
    return NextResponse.json(
      { error: 'Error al crear las preguntas' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const count = await prisma.valuesQuestion.count();
    return NextResponse.json({ count });
  } catch (error) {
    return NextResponse.json({ error: 'Error' }, { status: 500 });
  }
}
