import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db';

const STRESS_QUESTIONS = [
  // ESTRÉS LABORAL (1-6) - Higher value = more stress
  {
    questionNumber: 1,
    questionText: 'Me siento abrumado/a por la cantidad de trabajo que tengo que hacer.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 2,
    questionText: 'Tengo dificultades para desconectarme del trabajo al final del día.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 3,
    questionText: 'Experimento tensión física (dolor de cabeza, espalda, etc.) relacionada con el trabajo.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 4,
    questionText: 'Me preocupo constantemente por cumplir con los plazos y expectativas laborales.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 5,
    questionText: 'Siento que las demandas laborales afectan mi bienestar general.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 6,
    questionText: 'Experimento dificultades para dormir debido a pensamientos sobre el trabajo.',
    dimension: 'ESTRES_LABORAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  
  // CAPACIDAD DE RECUPERACIÓN (7-12) - Higher value = better recovery
  {
    questionNumber: 7,
    questionText: 'Puedo recuperarme rápidamente después de situaciones estresantes.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 8,
    questionText: 'Tengo estrategias efectivas para manejar el estrés.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 9,
    questionText: 'Después de un día difícil, logro descansar y recargar energías.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 10,
    questionText: 'Practico actividades que me ayudan a relajarme y desestresarme.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 11,
    questionText: 'Puedo identificar cuándo necesito tomarme un descanso.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 12,
    questionText: 'Me recupero bien de los contratiempos y decepciones.',
    dimension: 'CAPACIDAD_RECUPERACION',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  
  // MANEJO EMOCIONAL (13-18) - Higher value = better emotional management
  {
    questionNumber: 13,
    questionText: 'Puedo mantener la calma bajo presión.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 14,
    questionText: 'Reconozco y acepto mis emociones sin juzgarme.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 15,
    questionText: 'Puedo expresar mis emociones de manera constructiva.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 16,
    questionText: 'Controlo mis reacciones emocionales en situaciones difíciles.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 17,
    questionText: 'Me siento desbordado/a por mis emociones negativas.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 18,
    questionText: 'Pierdo el control emocional cuando estoy bajo estrés.',
    dimension: 'MANEJO_EMOCIONAL',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  
  // EQUILIBRIO VIDA-TRABAJO (19-24)
  {
    questionNumber: 19,
    questionText: 'Logro mantener un buen equilibrio entre mi vida personal y laboral.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: false,
  },
  {
    questionNumber: 20,
    questionText: 'Tengo tiempo suficiente para mis actividades personales y hobbies.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: false,
  },
  {
    questionNumber: 21,
    questionText: 'Mis responsabilidades laborales interfieren con mi vida familiar o personal.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  {
    questionNumber: 22,
    questionText: 'Puedo establecer límites claros entre el trabajo y la vida personal.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: false,
  },
  {
    questionNumber: 23,
    questionText: 'Dedico tiempo de calidad a las personas importantes en mi vida.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: false,
  },
  {
    questionNumber: 24,
    questionText: 'Me siento culpable cuando no estoy trabajando.',
    dimension: 'EQUILIBRIO_VIDA',
    category: 'NEGATIVE',
    optionA: 'Nunca',
    optionB: 'Raramente',
    optionC: 'A veces',
    optionD: 'Frecuentemente',
    optionE: 'Siempre',
    isReversed: false,
  },
  
  // RESILIENCIA GENERAL (25-30) - Higher value = more resilient
  {
    questionNumber: 25,
    questionText: 'Veo los desafíos como oportunidades de crecimiento.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 26,
    questionText: 'Mantengo una actitud positiva incluso en tiempos difíciles.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 27,
    questionText: 'Confío en mi capacidad para superar obstáculos.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 28,
    questionText: 'Aprendo de mis errores y experiencias negativas.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 29,
    questionText: 'Tengo una red de apoyo (familia, amigos, colegas) a la que puedo recurrir.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
  {
    questionNumber: 30,
    questionText: 'Me adapto bien a los cambios y situaciones inesperadas.',
    dimension: 'RESILIENCIA',
    category: 'POSITIVE',
    optionA: 'Totalmente en desacuerdo',
    optionB: 'En desacuerdo',
    optionC: 'Neutral',
    optionD: 'De acuerdo',
    optionE: 'Totalmente de acuerdo',
    isReversed: true,
  },
];

export async function POST() {
  try {
    // Check if questions already exist
    const existingCount = await prisma.stressQuestion.count();
    
    if (existingCount > 0) {
      return NextResponse.json({
        success: true,
        message: `Ya existen ${existingCount} preguntas de Estrés en la base de datos`,
        count: existingCount,
      });
    }
    
    // Create all questions
    const createdQuestions = await prisma.stressQuestion.createMany({
      data: STRESS_QUESTIONS.map(q => ({
        questionNumber: q.questionNumber,
        questionText: q.questionText,
        dimension: q.dimension as any,
        category: q.category as any,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        optionE: q.optionE,
        isReversed: q.isReversed,
        weight: 1.0,
        isActive: true,
      })),
    });
    
    return NextResponse.json({
      success: true,
      message: `Se crearon ${createdQuestions.count} preguntas de Estrés y Resiliencia`,
      count: createdQuestions.count,
    });
  } catch (error) {
    console.error('Error seeding stress questions:', error);
    return NextResponse.json(
      { error: 'Error al crear las preguntas de estrés' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const count = await prisma.stressQuestion.count();
    return NextResponse.json({ count });
  } catch (error) {
    return NextResponse.json({ error: 'Error al consultar preguntas' }, { status: 500 });
  }
}
